trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: servicenowStage
    jobs:
      - job: ServiceNow_job
        pool: server
        steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
           connectedServiceName: 'dev271065-Globex-ServiceNow DevOps Service Connection'
           changeRequestDetails:  |
            {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by": {
                    "user_name": "abel.tuter"
                  },
                  "start_date": "2025-01-05 08:00:00",
                  "end_date": "2025-01-08 08:00:00"
                }
              }
