trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build_Job_A
        steps:
          - script: echo This is the first Build Job!
  - stage: Test
    jobs:
     - job: Test_Job_A
       steps:
        - script: echo This is the first Test Job!

  - stage: Prod_Deploy    
    jobs:
     - job: Prod_Job_A
       pool: server
       steps:
#- script: echo This is the first Prod-deploy Job!
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'sysintegraptyltddemo17-Sysintegra DevOps Onboard-ServiceNow DevOps Service Connection'
            changeRequestDetails: |              
              {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by": {
                    "user_name": "Abel.tuter"
                  },
                  "assignment_group": {
                    "name": "Software"
                  },
                  "start_date": "2025-01-05 08:00:00",
                  "end_date": "2025-01-08 08:00:00",
                  "work_notes": "Testing DevOps Change Velocity"
                }
              }