trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - script: echo "This is the planning phase of the request."
  - stage: Sandbox
    jobs:
     - job: 
       steps:
        - script: echo "This is the development phase of the request."
  - stage: Dev
    jobs:
     - job: 
       steps:
        - script: echo "This is the code deployment phase to test instance."
  - stage: QA/UAT
    jobs:
     - job: 
       steps:
        - script: echo "This is the UAT testing phase of the request."
        
  - stage: Prod    
    jobs:
     - job: 
       pool: server
       steps:
#- script: echo This is the production deployement phase!
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'sysintegraptyltddemo17-Sysintegra DevOps Onboard-ServiceNow DevOps Service Connection'
            changeRequestDetails: |              
              {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by": {
                    "user_name": "Abel.tuter"
                  },
                  "assignment_group": {
                    "name": "Software"
                  },
                  "start_date": "2025-01-05 08:00:00",
                  "end_date": "2025-01-08 08:00:00",
                  "work_notes": "Testing DevOps Change Velocity"
                }
              }
