stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo Build Phase
  - stage: Dev
    jobs:
     - job: Initial Source
       steps:
        - script: echo Dev Phase
   - stage: QA
    jobs:
     - job: Unit_Test
       steps:
        - script: echo Unit Testing Phase

   - stage: UAT
    jobs:
     - job: Regression_Test
       steps:
        - script: echo UAT Testing Phase

   - stage: Prod  
    jobs:
     - job: Final_Deployment
       pool: server
       steps:
#- script: echo This is the first Prod-deploy Job!
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
           connectedServiceName: 'sysintegraptyltddemo17-Sysintegra DevOps Onboard-ServiceNow DevOps Service Connection'
            changeRequestDetails:  |
            {
                "setCloseCode" : true,
                "attributes": {
                  "requested_by": {
                    "user_name": "Abel.tuter"
                  },
                  "assignment_group": {
                    "name": "App Engine Admins"
                  },
                  "start_date": "2025-01-05 08:00:00",
                  "end_date": "2025-01-08 08:00:00",
                  "cab_required": "true",
                  "priority": 2,
                  "work_notes": "Text from devops"
                }
              }